---
- name: Install minion
  hosts: main
  remote_user: minion
  become: true
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

  tasks:
    # - name: yum upgade all
    #   ansible.builtin.yum:
    #     name: '*'
    #     state: latest
        
    - name: install required packages
      ansible.builtin.yum:
        name:
          - langpacks-en 
          - glibc-all-langpacks
          - java-11-openjdk-headless
          - telnet
          - net-tools
          - yum-utils
          - epel-release
          - firewalld
        state: latest
        update_cache: true
      
    - name: start firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: open ports
      ansible.posix.firewalld:
        port: 8980/tcp
        zone: public
        permanent: true
        state: enabled
    
    - name: open ports
      ansible.posix.firewalld:
        port: 61616/tcp
        permanent: true
        state: enabled   

    - name: reload firewalld
      ansible.builtin.shell:
        cmd: sudo firewall-cmd --reload

    - name: download yum key
      ansible.builtin.rpm_key:
        key: https://yum.opennms.org/OPENNMS-GPG-KEY
        state: present

    - name: add minion repo
      ansible.builtin.shell:
        cmd: sudo dnf -y install https://yum.opennms.org/repofiles/opennms-repo-stable-rhel9.noarch.rpm 

    - name: install horizon minion package
      ansible.builtin.yum:
        name: opennms-minion
        state: present
        update_cache: yes
        disable_gpg_check: yes        

    - name: Ensure OpenNMS is started and enabled
      ansible.builtin.systemd:
        name: minion
        enabled: yes
        state: started
